django/conf/project_template/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

ias/urls.py
from django.conf.urls.defaults import *
from django.views.generic import ListView

from ias.models import Sighting, Taxon


urlpatterns = patterns('',
    url('^sighting/$',
        ListView.as_view(
            model=Sighting,
            queryset=Sighting.objects.filter(verified=True)
        ),
        name='ias-sighting-list'
    ),
    url('^sighting/add/$',
        'ias.views.sighting_add',
        name="ias-sighting-add",
    ),
    url('^sighting/(\d+)$',
        'ias.views.sighting_detail',
        name='ias-sighting-detail'
    ),
    # URL for mobile redirect
    url('^sighting/(\d+)/(inApp)$',
        'ias.views.sighting_detail',
        name='ias-sighting-detail'
    ),
    url('^taxon/$',
        ListView.as_view(model=Taxon, queryset=Taxon.actives.all()),
        name="ias-taxon-list"
    ),
    url('^taxon/add/$',
        'ias.views.taxon_add',
        name="ias-taxon-add"
    ),
    url('^taxon/(\d+)/$',
        'ias.views.taxon_detail',
        name="ias-taxon-detail"
    ),
    url('^map/$',
        'ias.views.map',
        name="ias-map"
    ),
    url('^map/get_data/$',
        'ias.views.map_data',
        name="ias-map-data"
    ),
    url(r'^search/', 'ias.views.search_db', name='search-db'),
    url(r'^resave/', 'ias.views.resave', name='resave'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),
    url('^about$', 'django.views.generic.simple.direct_to_template',
     {'template': 'about.html'}, name="about"),
    url('^$', 'ias.views.home', name="home"),
    ('^ias/', include('ias.urls')),
    ('^admin/', admin.site.urls),
    ('^accounts/', include('registration.urls')),
    ('^importer/', include('importer.urls')),
    ('^api/', include('api.urls')),
)

ias/models.py
"""Models for IAS app - Species and Sightings."""
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

import tagging

from google.appengine.api import images as images_api
from google.appengine.api import files
from google.appengine.ext import blobstore


TAXA_CHOICES = (
    ('SPECIES', 'Species'),
    ('GENUS', 'Genus'),
    ('FAMILY', 'Family'),
    ('ORDER', 'Order'),
    ('CLASS', 'Class'),
    ('PHYLUM', 'Phylum'),
    ('KINGDOM', 'Kingdom'),
    ('DOMAIN', 'Domain'),
)


class TaxonManager(models.Manager):
    def get_query_set(self):
        return super(TaxonManager, self).get_query_set().filter(active=True)


class Taxon(models.Model):
    """A thing to sight, could be a group or a single species."""
    scientific_name = models.CharField(max_length=200)
    common_name = models.CharField(max_length=200)
    rank = models.CharField(choices=TAXA_CHOICES, max_length=50)
    key_text = models.TextField(help_text="A helpful description so that users"
        " can identify this taxon easily.")
    questionnaire = models.CharField(
        max_length=100,
        help_text="Where is the Google Questionnaire to which users should "
        "fully answer their sighting."
    )
    active = models.BooleanField(default=False, help_text="Has this been OK'd?")
    style_name = models.CharField(max_length=30, null=True, blank=True)
    style_json = models.TextField(null=True, blank=True)

    objects = models.Manager()
    actives = TaxonManager()

    def verified_sightings(self):
        return self.sightings.filter(verified=True)

    def __unicode__(self):
        if self.common_name:
            return self.common_name
        else:
            return u'%s: %s' % (
                self.get_rank_display(), self.scientific_name)

    def get_absolute_url(self):
        return reverse('ias-taxon-detail', args=[self.pk])

    class Meta:
        verbose_name_plural = 'Taxa'

tagging.register(Taxon)


class TaxonExpert(models.Model):
    expert = models.ForeignKey(User)
    taxon = models.ForeignKey(Taxon)

    def __unicode__(self):
        return "%s for %s" % (
            self.taxon,
            self.expert)


class Photo(models.Model):
    """An model to hold all the blobstore stuff."""
    photo = models.FileField(upload_to="photo", null=True)
    blob_key = models.CharField(max_length=256, null=True)
    url = models.CharField(max_length=256, null=True)

    def save(self, *args, **kwargs):
        if self.blob_key:
            self.url = images_api.get_serving_url(self.blob_key)
        super(Photo, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if self.blob_key:
            blobstore.delete(self.blob_key)
        super(Photo, self).delete(*args, **kwargs)

    def get_absolute_url(self, size=0, crop=False):
        if size:
            url = ''.join([self.url, '=s', str(size)])
            if crop:
                url = '-'.join([url, 'c'])
            return url
        else:
            return self.url

    def __unicode__(self):
        if not self.url:
            return "I have no url!, why?!"
        return self.get_absolute_url()


class Sighting(models.Model):
    
    """An instance of some user seeing some thing."""
    class Meta:
        ordering = ['-datetime']
    taxon = models.ForeignKey(
        Taxon,
        related_name="sightings",
        limit_choices_to={'active': True}
    )
    email = models.EmailField(null=True, blank=True, help_text="You may add an "
        "email address if you wish...")
    contactable = models.BooleanField(default=True)
    datetime = models.DateTimeField()
    lat = models.DecimalField(decimal_places=16, max_digits=20)
    lon = models.DecimalField(decimal_places=16, max_digits=20)
    photo = models.ForeignKey(Photo, related_name="sightings", null=True, blank=True)
    
    has_completed_questionnaire = models.BooleanField(default=False)
    
    verified = models.BooleanField(default=False)
    examplary = models.BooleanField(default=False)

    # wee bit of denormalisation
    taxon_name = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('ias-sighting-detail', args=[self.pk])

    def save(self, *args, **kwargs):
        if self.taxon:
            self.taxon_name = self.taxon.common_name \
                or self.taxon.scientific_name
        super(Sighting, self).save(*args, **kwargs)

    def __unicode__(self):
        return u"%s on %s" % (self.taxon, self.datetime.date())

ias/forms.py
from decimal import Decimal
import datetime

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.admin import widgets

from ias.models import Sighting, Taxon
from ias.exif_utils import get_lat_lon, get_datetime
from ias import widgets as ias_widgets

from EXIF import process_file


class SightingForm(forms.ModelForm):
    image = forms.FileField(help_text="Must be less than 1MB.")

    get_coords_from_photo = forms.BooleanField(
        required=False,
        initial=True,
        label="Get GPS from photo",
        help_text="Only available if your camera supports GPS.")
    lat = forms.DecimalField(
        max_digits=20,
        required=False,
        widget=forms.TextInput(attrs={
            'maxlength':20,
        }))
    lon = forms.DecimalField(
        max_digits=20,
        required=False,
        widget=forms.TextInput(attrs={
            'maxlength':20,
        }))
    map_picker = forms.CharField(
        widget=ias_widgets.GoogleLatLon(
            lat_name='lat', lon_name='lon'),
        required=False,
        help_text="Click on the map to choose a point",
        label="Click a point")

    get_datetime_from_photo = forms.BooleanField(
        required=False,
        initial=True,
        label="Get Date/time from photo",
        help_text="Likely to be available; will use current date/time.")
    date_time = forms.DateTimeField(
        widget=widgets.AdminSplitDateTime,
        required=False)

    class Meta:
        model = Sighting
        exclude = ('photo', 'has_completed_questionnaire',
                   'datetime', 'verified')
        fields = (
            'taxon', 'email', 'contactable', 'image',
            'get_coords_from_photo', 'lat', 'lon', 'map_picker',
            'get_datetime_from_photo', 'date_time'
        )

    def clean(self):
        """{'image': <InMemoryUploadedFile: Photo 04-08-2011 19 51 15.jpeg
        (image/jpeg)>, 'lon': None, 'taxon': <Taxon: Family: Fallopia>,
        'datetime': u"[u'', u'']", 'lat': None, 'contactable': True,
        'get_coords_from_photo': True, 'get_datetime_from_photo': True,
        'email': u'steve@synfinity.net'}"""
        c_data = self.cleaned_data
        if c_data.get('contactable', False) and \
            not c_data.get('email', ''):
            msg = "Please add email address if you want to be contacted!"
            self._errors["email"] = self.error_class([msg])
            del c_data['email']

        exif = None
        try:
            f = c_data['image'].file
            f.seek(0)
            exif = process_file(f)
        except Exception, e:
            import logging
            logging.error(e)
            exif = None

        if c_data.get('get_coords_from_photo') and exif:
# User thinks there is GPS data in EXIF, and we have EXIF
            lat, lon = get_lat_lon(exif)
            if lat and lon:
                c_data['lat'] = Decimal(str(lat))
                c_data['lon'] = Decimal(str(lon))
            else:
# There isn't! Uncheck the box (set False) (doesn't work.. hm.)
                msg = "No GPS info in EXIF data. Please add manually! :-(" 
                self._errors["get_coords_from_photo"] = self.error_class(
                    [msg])
                c_data["get_coords_from_photo"] = False
        elif c_data.get('get_coords_from_photo') and not exif:
# User thinks there is EXIF but there isnt any
            msg = "No EXIF data available to get GPS info :-(" 
            self._errors["get_coords_from_photo"] = self.error_class(
                [msg])
            c_data["get_coords_from_photo"] = False
        elif not c_data['lon'] or not c_data['lat']:
# User put in one of lat/lon but not both
            msg = "Must set Lat/Long coordinates!" 
            self._errors["lat"] = self.error_class(
                [msg])
            del c_data["lat"]
            self._errors["lon"] = self.error_class(
                [msg])
            del c_data["lon"]
        else:
# Didn't expect EXIF, all ok.
            c_data['lat'] = Decimal(c_data['lat'])
            c_data['lon'] = Decimal(c_data['lon'])


        if c_data.get('get_datetime_from_photo') and exif:
            dt = get_datetime(exif)
            if dt:
                c_data['date_time'] = str(dt)
            else:
                msg = "No date-time available in EXIF data. Please add manually! :-("
                self._errors["get_datetime_from_photo"] = self.error_class(
                    [msg])
                del c_data["get_datetime_from_photo"]
        elif c_data.get('get_datetime_from_photo') and not exif:
            msg = "No EXIF data available to get date-time info :-(" 
            self._errors["get_datetime_from_photo"] = self.error_class(
                [msg])
            del c_data["get_datetime_from_photo"]

        return c_data


class RegisterTaxonForm(forms.ModelForm):

    class Meta:
        model = Taxon
        exclude = ('active', 'style_name', 'style_json')


class AuthenticationRegisterForm(forms.Form):
    username = forms.CharField(label=("Email"), max_length=30)
    password = forms.CharField(label=("Password"), widget=forms.PasswordInput)

search/forms.py
from django import forms

class LiveSearchField(forms.CharField):
    def __init__(self, src, multiple_values=False, select_first=False,
                 auto_fill=False, must_match=False, match_contains=True,
                 **kwargs):
        attrs = {'src': src}
        classes = []
        if multiple_values:
            classes.append('multiple-values')
        if select_first:
            classes.append('select-first')
        if auto_fill:
            classes.append('auto-fill')
        elif match_contains:
            classes.append('match-contains')
        if must_match:
            classes.append('must-match')
        if classes:
            attrs['class'] = ' '.join(classes)
        super(LiveSearchField, self).__init__(
            widget=forms.TextInput(attrs=attrs), **kwargs)

search/views.py
from django.conf import settings
from djangotoolbox.http import JSONResponse

def live_search_results(request, model, search_index='search_index', limit=30,
        result_item_formatting=None, query_converter=None,
        converter=None, redirect=False):
    """
    Performs a search in searched_model and prints the results as
    text, so it can be used by auto-complete scripts.

    limit indicates the number of results to be returned.

    A JSON file is sent to the browser. It contains a list of
    objects that are created by the function indicated by
    the parameter result_item_formatting. It is executed for every result
    item.
    Example:
    result_item_formatting=lambda course: {
        'value': course.name + '<br />Prof: ' + course.prof.name,
        'result': course.name + ' ' + course.prof.name,
        'data': redirect=='redirect' and
            {'link': course.get_absolute_url()} or {},
    }
    """
    query = request.GET.get('query', '')
    try:
        limit_override = int(request.GET.get('limit', limit))
        if limit_override < limit:
            limit = limit_override
    except:
        pass
    search_index = getattr(model, search_index)
    language = getattr(request, 'LANGUAGE_CODE', settings.LANGUAGE_CODE)
    results = search_index.search(query, language=language)
    if query_converter:
        results = query_converter(request, results)
    results = results[:limit]
    if converter:
        results = converter(results)
    data = []
    for item in results:
        if result_item_formatting:
            entry = result_item_formatting(item)
        else:
            value = getattr(item, search_index.fields_to_index[0])
            entry = {'value': force_escape(value), 'result': value}
        if 'data' not in entry:
            entry['data'] = {}
        if redirect:
            if 'link' not in entry['data']:
                entry['data']['link'] = item.get_absolute_url()
        data.append(entry)
    return JSONResponse(data)

ias/templates/ias/base.html
<!DOCTYPE html>
<html>
    <head>
    {% block title %}
        IAS-ESS
    {% endblock %}
    {% block css %}
        <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0b1/jquery.mobile-1.0b1.min.css" />
    {% endblock %}
    {% block preload-js %}
    	{% comment %}<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.1.min.js"></script>
	    <script type="text/javascript" src="http://code.jquery.com/mobile/1.0b1/jquery.mobile-1.0b1.min.js"></script>{% endcomment %}
    {% endblock %}
    </head>
    <body>
        <div data-role="header" data-theme="b">
            <h1>{% block header %}IAS-ESS{% endblock %}</h1>
        </div>
        {% block content %}
            <div data-role="page" data-theme="b">
                <div data-role="content">
                    {% block content %}{% endblock %}
                </div>
            </div>
        {% endblock %}


        <div data-role="footer" data-position="fixed">
            <h1>&copy; ias-ess.org</h1>
        </div>
    </body>
</html>

ias/templates/ias/map.html
{% extends "base.html" %}
{% load utils %}
{% load ias_tags %}

{% block extra-head %}
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<link rel="stylesheet"  media="all" type="text/css" href="{{ STATIC_URL }}css/sections.css" />
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/markerclusterer-r317.js"></script>
<script type="text/javascript">{% include "ias/map_styles.js" %}</script>
<script type="text/javascript" src="/appmedia/js/map.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        var data = $.parseJSON('{{ map_data|safe }}');
        var get_data_url = "{% url ias-map-data %}";
        var config = {"data": data, "get_data_url": get_data_url};
        initialize_map(config);
    });
</script>
{% endblock %}

{% block page %}map-page{% endblock %}
{% block navclass %}map-nav{% endblock %}

{% block content %}
<section class="generic-inner">
    <h1>Sighting details</h1>
    <div id="map_container" >
        <div id="map_canvas" ></div>
    </div>
    <div id="map_hidden_canvas" style="display: none"></div>

    {% for taxon in taxa %}
    <div class="form-row checkbox-row">
    <input type="checkbox" id="cluster{{ taxon.pk }}" checked />{{ taxon }}
    </div>
    {% endfor %}

    <form action="{% url ias-map-data %}" method="POST" id="download_map_data_form">
        {% csrf_token %}
        <input id="download_map_data_input" type="hidden" name="" value="">
    </form>
    <p></p><a href="" id="get_marker_data">Download visible data in viewport</a></p>

  </section>
{% endblock %}

ias/templates/ias/search.html
{% extends 'base.html' %}

{% block css %}
<link rel="stylesheet"  media="all" type="text/css" href="{{ STATIC_URL }}css/sections.css" />
{% endblock %}

{% block page %}search-results-page{% endblock %}


{% block content %}

<article class="generic-inner">


<h1>Search Results</h1>
{% for taxon in taxa %}
 <ul class="search-list search-taxon">
        <li><a href="{{ taxon.get_absolute_url }}">{{ taxon }}</a></li>
 </ul>
{% endfor %}

{% for sighting in sightings %}
 <ul class="search-list search-sighting">
        <li><a href="{{ sighting.get_absolute_url }}">{{ sighting }}</a></li>
 </ul>
{% endfor %}





</article>
{% endblock %}

ias/templates/ias/sighting.html
{% extends "base.html" %}
{% load setting_tag %}

{% block css %}
<link rel="stylesheet"  media="all" type="text/css" href="{{ STATIC_URL }}css/sections.css" />
<link rel="stylesheet" type="text/css" href="{% setting ADMIN_MEDIA_PREFIX %}css/widgets.css"/>
{% endblock %}

{% block preload-js %}
{{ block.super }}
{% load adminmedia %}
<script type="text/javascript">
window.__admin_media_prefix__ = "{% filter escapejs %}{% admin_media_prefix %}{% endfilter %}";
</script>
{% endblock %}

{% block extra-head %}
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="{% setting ADMIN_MEDIA_PREFIX %}js/core.js"></script>
{{ form.media }}
{% endblock %}

{% block navclass %}sightings-nav{% endblock %}

{% block content %}

<section class="generic-inner">
    <h1>Add a sightings</h1>
<form method="post" id="sighting-form" action="{{ action }}" enctype="multipart/form-data">
    {% csrf_token %}
    {% include "form_snippet.html" %}
    <input class="input-submit"type="submit" name="submit" value="submit" />
</form>
</section>
{% endblock %}

{% block js %}
<script type="text/javascript">
    {% if user.is_authenticated %}
    $('#id_email').val('{{ user.email }}');
    {% endif %}

    if ($('#id_get_coords_from_photo').attr('checked')) {
        if ($('#id_get_coords_from_photo').next().hasClass('errorlist')) {
            $('#id_get_coords_from_photo').prop('checked', false);
        } else {
            $('#id_lat').parent().toggle();
            $('#id_lon').parent().toggle();
            $('#id_map_picker').parent().toggle();
        }
    }
    $('#id_get_coords_from_photo').bind('change', function() {
        $('#id_lat').parent().toggle();
        $('#id_lon').parent().toggle();
        $('#id_map_picker').parent().toggle();
        initialize(); // the map
    });
    if ($('#id_get_datetime_from_photo').attr('checked')) {
        $('#id_date_time_0').parent().parent().toggle();
    }
    $('#id_get_datetime_from_photo').bind('change', function() {
        $('#id_date_time_0').parent().parent().toggle();
    });
</script>
{% endblock %}

ias/templates/ias/sighting_detail.html
{% extends "base.html" %}
{% load ias_tags %}
{% block css %}
<link rel="stylesheet"  media="all" type="text/css" href="{{ STATIC_URL }}css/sections.css" />
<link rel="stylesheet"  media="all" type="text/css" href="{{ STATIC_URL }}css/google_form.css" />
{% endblock %}

{% block navclass %}sightings-nav{% endblock %}

{% block extra-head %}
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
{% if not in_app %}
<script type="text/javascript"
    src="http://maps.google.com/maps/api/js?sensor=true">
</script>
<script type="text/javascript">
function initialize() {
    var latlng = new google.maps.LatLng({{ sighting.lat }}, {{ sighting.lon }});
    var myOptions = {
      zoom: 8,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map_canvas"),
        myOptions);

    var make_marker = function(photo, lat, lng, map) {
        var infowindow = new google.maps.InfoWindow({
            content: '<img src="' + photo + '" alt="photo" />'
        });

        var latlng = new google.maps.LatLng(lat, lng);

        var marker = new google.maps.Marker({
            position: latlng,
            map: map,
            title:"{{ sighting.taxon }}"
          });
        google.maps.event.addListener(marker, 'click', function() {
            infowindow.open(map, marker);
        });
    };

    {% for sight in others %}
    make_marker(
        '{{ sight.photo|size:400 }}',
        {{ sight.lat }},
        {{ sight.lon }},
        map);
    {% endfor %}

    make_marker(
        '{{ sighting.photo|size:400 }}',
        {{ sighting.lat }},
        {{ sighting.lon }},
        map);
}


</script>
{% endif %}
{% endblock %}

{% block body-onload %}{% if not in_app %}initialize();{% endif %}{% endblock %}

{% block content %}
<section class="generic-inner">
    <h1>Sighting details</h1>
    <div class="detail-wrapper">
        {% if not in_app %}
        <div class="pic-holder"><img src='{{ sighting.photo }}' alt='photo' /></div>  

        <ul class="detail-list">
            <li><strong>Taxon:</strong><br /> {{ sighting.taxon }}</li>
            {% if sighting.contactable %}
                <li><strong>Reported by: <br /></strong> {{ sighting.email }}</li>
            {% endif %}
            <li><strong>On:</strong> <br/ > {{ sighting.datetime }}</li>
            
        </ul>
        {% endif %}
        </div>

        {% if google_form %}
        <a name="Questionnaire" ><h2>A few more details...</h2></a>
        {# This little JS/iframe hack allows us to redirect here #}
        <script type="text/javascript">var submitted=false;</script>
        <iframe
        name="hidden_iframe"
        id="hidden_iframe"
        style="display:none;"
        onload="if (submitted)
                {window.location='{% url ias-sighting-detail sighting.pk %}';}">
        </iframe>
        {{ google_form|safe }}
        {% endif %}

        {% if not in_app %}
        <div id="map_container" >
            <div id="map_canvas" ></div>
        </div>
        {% endif %}
{% endblock %}

ias/templates/ias/sighting_done.html
{% extends "ias/base.html" %}

{% block content %}
Thanks for submitting your sighting!
{% endblock %}

ias/templates/ias/sighting_list.html
{% extends 'base.html' %}
{% load ias_tags %}

{% block css %}
<link rel="stylesheet"  media="all" type="text/css" href="{{ STATIC_URL }}css/sections.css" />
{% endblock %}

{% block preload-js %}
{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.tablesorter.min.js"></script>
{% endblock %}

{% block page %}sightings-page{% endblock %}
{% block navclass %}sightings-nav{% endblock %}

{% block content %}
    <section class="generic-inner">
        <h1>List of sightings</h1>
        <table id="sightings">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Date</th>
                    <th>Taxon</th>
                    <th>Sighter</th>                
                </tr>
            </thead>
            <tbody>
            {% for sighting in object_list %}
                <tr>
                    <td class="image-cell">
                         <a href="{{ sighting.get_absolute_url }}">
                        <img src="{{ sighting.photo|size:150 }}" alt="" />
                        </a>
                    </td>
                    
                    <td class="time-cell">
                        {{ sighting.datetime }}
                    </td>
                    <td class="taxon-cell">
                        <a href="{{ sighting.get_absolute_url }}">{{ sighting }}</a>
                    </td>
                    <td>
                    {% if sighting.contactable and user|is_expert_for:sighting %}
                    <a href="mailto:{{ sighting.email }}">{{ sighting.email }}</a>
                    {% endif %}
                    </td>
                    
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $('#sightings').tablesorter();
</script>
{% endblock %}

ias/templates/ias/taxon_list.html
{% extends 'base.html' %}
{% load ias_tags %}

{% block css %}
<link rel="stylesheet"  media="all" type="text/css" href="{{ STATIC_URL }}css/sections.css" />
{% endblock %}

{% block page %}taxa-page{% endblock %}
{% block navclass %}taxa-nav{% endblock %}

{% block content %}
<section class="generic-inner">
    <h1>List of taxa</h1>

    <ul id="taxa-list">
        {% for taxon in object_list %}
            <li>
                <a href="{{ taxon.get_absolute_url }}">{{ taxon }}</a>
            </li>
        {% endfor %}
    </ul>
</section>
{% endblock %}

ias/templates/ias/taxon_register.html
{% extends "base.html" %}

{% block title %} - Register IAS{% endblock %}

{% block css %}
<link rel="stylesheet"  media="all" type="text/css" href="{{ STATIC_URL }}css/sections.css" />
{% endblock %}

{% block content %}
<section class="generic-inner">
<h1>Register a new taxon for investigation</h1>

    <p>In order to register a new taxon for tracking, you will need to complete the following steps:<p>
  
  {% comment %}
    <ol>
        <li>Create a Google Form Questionnaire</li>
        <li>Register the basic details</li>
    </ol>
  {% endcomment %}


    <h2 class="step"><span>Step 01:</span> Create a Google Form Questionnaire</h2>
    <p>Below, you will see a Google Form template. Click 'Use this template' to
    create your own IAS questionnaire. This allows you to expand on the basic
    information available through ias-ass and will record all the data to a
    spreadsheet automatically.</p>
    <p>After creating this template, you can register the taxon. You will see a link
    at the bottom of the Google Form creation form like this, from which you should
    copy the form 'key' (everything after the equals sign):</p>
    <img src="{{ STATIC_URL }}img/examples/google-form.png" alt="Google Form" />
    <iframe
        width="620"
        height="170"
        frameborder="0"
        scrolling="no"
        marginheight="0"
        marginwidth="0"
        src="https://docs.google.com/embeddedtemplate?id=0AsUqypM_TuShdGMzdnRUZG5VdThad2ZoTUNSV2JMemc">
    </iframe>



    <h2 class="step"><span>Step 02:</span> Register the basic details</h2>
    <form id="basic-details" action="." method="POST">
        {% csrf_token %}
    {% include "form_snippet.html" %}
    <input type="submit" value="Register taxon" />
    </form>

</section>


{% endblock %}